name: Update Daily Fixtures
on:
  schedule:
    - cron: '0 */6 * * *' # Berjalan setiap 6 jam
  workflow_dispatch:

jobs:
  update-daily:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install
      - env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          FIREBASE_DB_URL: ${{ secrets.FIREBASE_DB_URL }}
          API_FOOTBALL_KEY: ${{ secrets.API_FOOTBALL_KEY }}
        run: node daily.js
