name: Update Live Score

on:
  schedule:
    - cron: '* * * * *' # Berjalan setiap 1 menit
  workflow_dispatch: # Mengizinkan eksekusi manual (tombol Run)

jobs:
  run-live-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install Dependencies
        run: npm install axios firebase-admin
        
      - name: Run index.js (Live Matches)
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          FIREBASE_DB_URL: ${{ secrets.FIREBASE_DB_URL }}
          API_FOOTBALL_KEY: ${{ secrets.API_FOOTBALL_KEY }}
        run: node index.js
